#!/bin/bash

# Run from the sessionj root directory:
# newBenchmark/eventSJ/make 


for f in ServerRunner ClientRunner Signal; do

    echo Compiling newBenchmark/eventSJ/$f.sj
    bin/sessionjc -cp tests/classes -sourcepath newBenchmark/eventSJ newBenchmark/eventSJ/$f.sj -d tests/classes
    if [ $? -ne 0 ]; then exit 1; else echo; fi

done
